<?php
/*
   ML framework
*/

class DatabaseException extends Exception {}

interface IDatabase {
    function query($sql);
        /* 
         * This method will take an SQL statement, 
         * query the database 
         * and return the results as an associative array.
         */
    function execute($sql);
        /*
         * This method will take an SQL statement and apply it to the database. 
         * It will return a count of the number of rows affected.
         */
    function executeBatch($list);
        /* 
         * This method will take an array of SQL statements and apply each of them to the database. 
         * It will return a count of the total number of rows affected.
         */
    function getInsertID();
        /* 
         * This method will return the last ID automatically generated by the connection. 
         * It is used when the database creates IDs, for example by auto_increment.
         */
    function close();
        /*
         * This method will close the database connection.
         */
}

?>